Issues addressed, working temperature sensor code
AccelerationConsortium/ac-dev-lab pull request #127
Opened 2024-12-08 16:00 UTC by Luthiraa

2025-03-01 20:43 UTC, sgbaird reviewed
There are several folders (the dist ones) and files (.mpy) that aren't necessary or are unused. Please remove. Please also remove any dependencies that aren't used (e.g., I see you have robust and simple, but the implementation should be with mqtt_as). If you're not using mqtt_as yet, you can refer to https://ac-microcourses.readthedocs.io/en/latest/courses/hello-world/1.4-hardware-software-communication.html and other [training lab IoLT examples](https://ac-training-lab.readthedocs.io/en/latest/devices/setup_iolt_devices.html#mqtt-orchestrator-and-device-code).

Please move this from `scripts` to https://github.com/AccelerationConsortium/ac-training-lab/tree/main/`src/ac_training_lab/picow/temp-humidity-pressure-gas-sensor` (you'll need to create the directory).

You committed secrets. Also, please rename to `my_secrets.py` locally and then add `my_secrets.py` to `.gitignore` so that you're not committing the secrets. These secrets should then be imported, not defined directly.

You might not need urequests_2.py anymore. I think you can just use regular `requests` as normal. Please double check though.

Please update and then ping me when ready for me to review again.

2025-03-01 20:45 UTC, sgbaird commented
Also, I'm not quite sure what the differences between this and https://github.com/AccelerationConsortium/ac-training-lab/pull/63 are. If these are duplicates, please close one and use a single branch / PR.

2025-03-12 04:49 UTC, Luthiraa commented
I'm not quite sure what's causing the merge conflict, as I took care of all the warnings that the pre-commit gave (flake, black, etc.). However, when I run flake, it gives me errors from other files (on occasion). When I run pre-commit, everything passes safely.

2025-03-12 12:58 UTC, sgbaird requested changes
Thanks for the updates!

There shouldn't be a separate pre-commit file for tempSensor: scripts/tempSensor/.pre-commit-config.yaml. I deleted

pico_id typically isn't something you should expose: scripts/tempSensor/pico_id.txt. I deleted

Again, you shouldn't have robust.py and simple.py in there, since you should only be using mqtt_as.py. Please adjust so that you're using mqtt_as.py, and you can follow the general approach shown in https://ac-microcourses.readthedocs.io/en/latest/courses/hello-world/1.4-hardware-software-communication.html and the module 4 assignment that you should have completed already.

If the LICENSE is attached with the bme680.py script, then please change the name of the LICENSE file to LICENSE_bme680.txt or put the LICENSE and bme680.py file within its own subdirectory.

Once you take care of this, and run pre-commit again, if it still isn't passing I'll go in and fix. Also, after making the changes, please verify that it still works with the corresponding HF Space.

2025-03-12 13:03 UTC, sgbaird commented
Aside: Next time it would be best to do this as a branch in ac-training-lab rather than in your own fork

2025-03-22 21:48 UTC, sgbaird commented on scripts/tempSensor/main.py
> +from umqtt.simple import MQTTClient
The script should be using mqtt_as, not mqtt.simple

2025-03-22 21:53 UTC, sgbaird requested changes
Thanks for addressing some of the concerns, @luthiraa. See a few remaining ones. Please check to make sure the script + HF is functioning correctly after you make the changes. After that, should be good to merge.

2025-03-22 21:53 UTC, sgbaird commented on scripts/tempSensor/main.py
> +SSID = "Pixel 8"
Please put all of this in a .gitgnore'd my_secrets.py file. You're exposing credentials publicly by committing.

2025-03-22 21:53 UTC, sgbaird commented on scripts/tempSensor/main.py
> +MQTT_BROKER = b"b6bdb89571144b3d8e5ca4bbe666ddb5.s1.eu.hivemq.cloud"
Shouldn't need the b, at least in mqtt_as

2025-03-22 21:53 UTC, sgbaird commented on scripts/tempSensor/main.py
> +def connect_to_wifi():
Not sure why you have an additional wrapper to connect WiFi. Maybe overkill

2025-03-25 00:56 UTC, sgbaird commented
Nice, thanks! Have you verified this works in tandem with HF? If so, I think we're good to merge.

2025-03-25 19:38 UTC, Luthiraa commented
Yes, this code works with the hf. Should I also include this code under a /scripts file for the space?

2025-03-25 20:08 UTC, sgbaird commented
That's OK, as long as the HF code is current. Can you copy the link to the HF space here?

2025-06-12 18:56 UTC, sgbaird commented
I believe it's this one - https://huggingface.co/spaces/AccelerationConsortium/temperature-sensor. Please let me know if otherwise

2025-06-16 20:08 UTC, Luthiraa commented
Yes, that is the one

2026-01-10 17:41 UTC, closed without merging

2026-09-18 16:32 UTC, sgbaird commented
Reposting three of my review comments from 2025-03-22 on `scripts/tempSensor/main.py` as a plain comment. The originals were deleted because GitHub's attached diff context displayed a contributor's personal Wi-Fi hotspot credentials (which were later moved to a git-ignored `my_secrets.py`, as requested below).

1. (config block) Please put all of this in a .gitgnore'd my_secrets.py file. You're exposing credentials publicly by committing.
2. (`MQTT_BROKER = b"..."`) Shouldn't need the b, at least in mqtt_as
3. (WiFi connect wrapper) Not sure why you have an additional wrapper to connect WiFi. Maybe overkill